spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lqb_gw
    password: DK3HY47hxeji86Le
    url: jdbc:mysql://106.52.176.28:3306/lqb_gw?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
    open-in-view: false
server:
  port: 8081
  servlet:
    context-path: /lqb
mybatis:
  type-aliases-package: com.example.lqb.model
  mapper-locations: classpath:mapper/*.xml